version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ticketing
      - JWT_SECRET=your-secret-key
      - ENVIRONMENT=development
    depends_on:
      - db
    volumes:
      - ./migrations:/app/migrations
    networks:
      - ticketing-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticketing
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing-network

volumes:
  postgres_data:

networks:
  ticketing-network:
    driver: bridge 